# -*- coding: utf-8 -*-
"""tweetdetector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/137IWgGAisH8zG-hc_SvrdwlK9ugvuRwO
"""

!pip install transformers datasets accelerate optuna shap spacy wordcloud
!python -m spacy download en_core_web_sm

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from wordcloud import WordCloud

import re
import spacy

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments
)

import torch

from google.colab import files
uploaded = files.upload()

train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
train.head()

train.shape

train.isnull().sum()

train['keyword'] = train['keyword'].fillna('unknown')
train['location'] = train['location'].fillna('unknown')

train.isnull().sum()

train['target'].value_counts()

train['target'].value_counts().plot(kind='bar')
plt.show()

from wordcloud import WordCloud , STOPWORDS
stopwords = set(STOPWORDS)
disaster_text = " ".join(train[train['target']==1]['text'])
wordcloud = WordCloud(width=800 , height=400 , stopwords=stopwords ).generate(disaster_text)
plt.figure(figsize = (12 , 6))
plt.imshow(wordcloud)
plt.show()

import re
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

def clean_text(text):

    # lowercase
    text = text.lower()

    # remove URLs
    text = re.sub(r'http\S+', '', text)

    # remove HTML entities like &amp;
    text = re.sub(r'&\w+;', '', text)

    # remove punctuation/numbers
    text = re.sub(r'[^a-z\s]', '', text)

    # remove stopwords
    words = text.split()
    words = [word for word in words if word not in stop_words]

    return " ".join(words)

train['clean_text'] = train['text'].apply(clean_text)
test['clean_text'] = test['text'].apply(clean_text)

disaster_text = " ".join(
    train[train['target']==1]['clean_text']
)

wordcloud = WordCloud(
    width=1000,
    height=500,
    background_color='white'
).generate(disaster_text)

plt.figure(figsize=(15,8))
plt.imshow(wordcloud)
plt.axis('off')
plt.show()

train['tweet_length'] = train['text'].apply(len)

train['word_count'] = train['text'].apply(
    lambda x:len(x.split())
)

train['caps_count'] = train['text'].apply(
    lambda x: sum(1 for c in x if c.isupper())
)

vectorizer = TfidfVectorizer(
    max_features=10000,
    ngram_range=(1,2),
    stop_words='english'
)

X = vectorizer.fit_transform(train['clean_text'])

y = train['target']

X_train, X_valid, y_train, y_valid = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

lr_model = LogisticRegression()

lr_model.fit(X_train, y_train)

lr_preds = lr_model.predict(X_valid)

print(
    accuracy_score(y_valid, lr_preds)
)

svm_model = LinearSVC()

svm_model.fit(X_train, y_train)

svm_preds = svm_model.predict(X_valid)

print(
    accuracy_score(y_valid, svm_preds)
)

from sklearn.metrics import confusion_matrix

import matplotlib.pyplot as plt
cn = confusion_matrix( y_valid, lr_preds)
plt.figure(figsize=(8, 6))
plt.imshow(cn)
plt.title('Confusion Matrix')
plt.colorbar()
plt.xlabel('Predicted')
plt.ylabel('True')
plt.show

from sklearn.metrics import classification_report
print(classification_report(y_valid, lr_preds))

"""Recall = 0.67 ⚠️

This is the IMPORTANT part.

Meaning:

Out of all REAL disaster tweets,
the model only detects:

67%

It MISSES:

33%

of disasters.
"""

wrong = train.iloc[:len(y_valid)]
wrong['pred'] = svm_preds
mistakes = wrong[wrong['target'] != wrong['pred']]

mistakes[['text', 'target', 'pred']].head(10)

import re
import string
import nltk

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')

stop_words = set(stopwords.words('english'))

lemmatizer = WordNetLemmatizer()

def clean_text_advanced(text):

    text = text.lower()

    # remove urls
    text = re.sub(r"http\S+", "", text)

    # remove mentions
    text = re.sub(r'@\w+', '', text)

    # keep hashtag words
    text = re.sub(r'#', '', text)

    # remove html entities
    text = re.sub(r'&\w+;', '', text)

    # remove numbers
    text = re.sub(r'\d+', '', text)

    # remove punctuation
    text = text.translate(
        str.maketrans('', '', string.punctuation)
    )

    # tokenize
    words = text.split()

    # remove stopwords + lemmatize
    words = [
        lemmatizer.lemmatize(word)
        for word in words
        if word not in stop_words and len(word) > 2
    ]

    return " ".join(words)

train['clean_text'] = train['text'].apply(
    clean_text_advanced
)

test['clean_text'] = test['text'].apply(
    clean_text_advanced
)

train['tweet_length'] = train['text'].apply(len)

train['word_count'] = train['text'].apply(
    lambda x: len(x.split())
)

train['caps_count'] = train['text'].apply(
    lambda x: sum(1 for c in x if c.isupper())
)

train['exclamation_count'] = train['text'].apply(
    lambda x: x.count('!')
)

train['question_count'] = train['text'].apply(
    lambda x: x.count('?')
)

train['hashtag_count'] = train['text'].apply(
    lambda x: x.count('#')
)

train['mention_count'] = train['text'].apply(
    lambda x: x.count('@')
)

train['url_count'] = train['text'].apply(
    lambda x: x.count('http')
)

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=30000,
    ngram_range=(1,3),
    min_df=2,
    max_df=0.95,
    sublinear_tf=True,
    stop_words='english'
)

X = vectorizer.fit_transform(
    train['clean_text']
)

y = train['target']

from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

from sklearn.svm import LinearSVC

model = LinearSVC(
    class_weight='balanced',
    C=1.2
)

model.fit(X_train, y_train)

preds = model.predict(X_valid)

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    accuracy_score,
    f1_score
)

print(
    "Accuracy:",
    accuracy_score(y_valid, preds)
)

print(
    "F1 Score:",
    f1_score(y_valid, preds)
)

print(
    classification_report(y_valid, preds)
)

import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_valid, preds)

plt.figure(figsize=(8,6))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")

plt.show()

valid_df = train.iloc[y_valid.index].copy()

valid_df['pred'] = preds

mistakes = valid_df[
    valid_df['target'] != valid_df['pred']
]

mistakes[['text', 'target', 'pred']].head(20)

!pip install transformers datasets accelerate

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments
)

import torch

train = train.sample(2000)
tokenizer = AutoTokenizer.from_pretrained(
    'bert-base-uncased'
)

train_encodings = tokenizer(
    train['text'].tolist(),
    truncation=True,
    padding=True,
    max_length=64
)

class DisasterDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

dataset = DisasterDataset(
    train_encodings,
    train['target'].tolist()
)

model = AutoModelForSequenceClassification.from_pretrained(
    'bert-base-uncased',
    num_labels=2)

training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=1,
    per_device_train_batch_size=8,
    warmup_steps=500,
    weight_decay=0.01,
    logging_dir='./logs',
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset
)

trainer.train()

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification
)

tokenizer = AutoTokenizer.from_pretrained(
    "./disaster_model"
)

model = AutoModelForSequenceClassification.from_pretrained(
    "./disaster_model"
)

print("✅ Model Loaded Successfully")

model.save_pretrained('./disaster_model')

tokenizer.save_pretrained('./disaster_model')

def predict_disaster(text):
   inputs = tokenizer(
        text,
        truncation=True,
        padding=True,
        max_length=64,
        return_tensors='pt')
   outputs = model(**inputs)
   probs = torch.nn.functional.softmax(outputs.logits, dim=-1)
   prediction = torch.argmax(probs).item()
   confidence = probs[0][prediction].item()

   return prediction, confidence

tweet = "Massive flood destroyed homes"

pred, conf = predict_disaster(tweet)

print(pred)
print(conf)
if pred == 1:
  print("Disaster")
else:
  print("Not a disaster")

tweet = "i love watching movies"

pred, conf = predict_disaster(tweet)

print(pred)
print(conf)

from IPython.display import HTML, display
import torch

# ---------------- HEADER ----------------

display(HTML("""
<div style="
padding:20px;
border-radius:12px;
color:white;
">

<h1>🚨 Disaster Tweet AI</h1>

<p>
Type a tweet and AI will predict whether
it describes a real disaster or not.
</p>

</div>
"""))

# ---------------- SAMPLE TWEETS ----------------

samples = [
    "Earthquake damaged buildings",
    "I love pizza 🍕",
    "Wildfire spreading rapidly",
    "This song is fire 🔥"
]

print("\n🧪 Sample Tweets:\n")

for s in samples:
    print("•", s)

# ---------------- PREDICTION FUNCTION ----------------

model.eval()

def predict_tweet(text):

    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=64
    )

    with torch.no_grad():

        outputs = model(**inputs)

    probs = torch.softmax(
        outputs.logits,
        dim=1
    )

    pred = torch.argmax(probs).item()

    conf = probs[0][pred].item()

    return pred, conf

# ---------------- MAIN APP ----------------

while True:

    print("\n" + "="*50)

    tweet = input("✍️ Enter Tweet: ")

    if tweet.lower() == "quit":

        print("\n👋 App Closed")
        break

    pred, conf = predict_tweet(tweet)

    print("\n📢 RESULT")
    print("-"*30)

    if pred == 1:

        print("🚨 Disaster Tweet")

    else:

        print("✅ Non-Disaster Tweet")

    print(f"\n🎯 Confidence: {conf:.2%}")

    # ---------------- SIMPLE STATS ----------------

    words = len(tweet.split())

    chars = len(tweet)

    print("\n📊 Quick Stats")
    print("-"*30)

    print(f"📝 Words: {words}")
    print(f"🔠 Characters: {chars}")